execution_engine: asyncio
logger:
  type: file
  level: debug
  path: "logs/multi-code-reviewer.jsonl"

mcp:
  servers:
    # GitHub MCP server
    github:
      command: 'npx'
      args: ['-y', '@modelcontextprotocol/server-github']

    # Git MCP server (optional - if needed for deeper repo analysis)
    git:
      command: 'uvx'
      args: ['mcp-server-git']

    # Fetch server for accessing web resources
    fetch:
      command: 'uvx'
      args: ['mcp-server-fetch']

    # File system server for accessing local files
    file:
      command: 'npx'
      args: [
        "-y",
        "@modelcontextprotocol/server-filesystem",
        "/tmp/pr_checkout"
      ]
