[project]
name = "prismatic"
version = "0.1.0"
description = "An AI Agent for reviewing GitHub pull requests"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.49.0",
    "gitpython>=3.1.44",
    "mcp-agent>=0.0.7",
    "pygithub>=2.6.1",
]
